# Generated by Django 3.0.4 on 2020-03-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.branch')),
            ],
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user_profile')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_role',
            field=models.ManyToManyField(through='user.user_roles', to='user.roles'),
        ),
        migrations.AddField(
            model_name='branch',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.college'),
        ),
    ]
