# Generated by Django 3.0.4 on 2020-03-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='user_roles',
            table='user_roles',
        ),
    ]
