# Generated by Django 3.0.4 on 2020-04-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='interview_exp',
        ),
        migrations.AddField(
            model_name='interview_experience',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='picture',
            field=models.ImageField(upload_to='!@#khdkjashd821939812!@#!@#__jnd'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
