# Generated by Django 3.0.4 on 2020-04-25 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200423_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ManyToManyField(through='user.user_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
