# Generated by Django 3.0.4 on 2020-04-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200329_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_roles',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user_roles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='college',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='user_roles',
        ),
    ]
