# Generated by Django 3.0.4 on 2020-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200403_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='college',
        ),
        migrations.DeleteModel(
            name='roles',
        ),
    ]
