# Generated by Django 3.0.4 on 2020-04-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_branch_college_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('modified_date', models.DateField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('password', models.CharField(max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.college')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_profile')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_role',
            field=models.ManyToManyField(through='user.user_roles', to='user.roles'),
        ),
    ]
