# Generated by Django 3.0.4 on 2020-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
